version: '3'
services:
  web:
    image: 'twang2218/gitlab-ce-zh'
    restart: always
    hostname: '192.168.118.8'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.118.8:8080'
        gitlab_rails['gitlab_shell_ssh_port']=2222
        unicorn['port']=8888
        nginx['listen_port']=8080
    ports:
      - '8080:8080'
      - '8443:443'
      - '2222:22'
    volumes:
      - ./data/git-data/:/var/opt/gitlab/git-data
      - ./data/sql-data:/var/opt/gitlab/postgresql/data




# ====================            数据迁移
# 第一步: 把整个目录复制到linux 某个目录下，
# 第二步：docker-compose up -d 启动    docker-compose logs -f 等待报错
# 第三步：docker-compose down  停止
# 第四步：修改权限 chmod -R 700 ./data/sql-data
# 第五步：docker-compose up -d 启动



